from enum import Enum


class NotificationType(str, Enum):
    APPLICATION_SUBMITTED = "APPLICATION_SUBMITTED"
    APPLICATION_STATUS_CHANGED = "APPLICATION_STATUS_CHANGED"
    MISSING_DOCUMENTS = "MISSING_DOCUMENTS"

    APPLICATION_ASSIGNED = "APPLICATION_ASSIGNED"

    EVALUATION_STARTED = "EVALUATION_STARTED"
    EVALUATION_COMPLETED = "EVALUATION_COMPLETED"

    FINAL_DECISION = "FINAL_DECISION"

    DEADLINE_REMINDER = "DEADLINE_REMINDER"