"""create committee members table

Revision ID: 08b2dfcaf92a
Revises: 0e589007dedf
Create Date: 2026-08-03 00:57:23.165162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b2dfcaf92a'
down_revision: Union[str, Sequence[str], None] = '0e589007dedf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committee_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_in_committee', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role_in_committee IN ('CHAIR', 'MEMBER', 'SECRETARY')", name='ck_committee_member_role'),
    sa.ForeignKeyConstraint(['committee_id'], ['evaluation_committees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('committee_id', 'user_id', name='uq_committee_member_user')
    )
    op.create_index(op.f('ix_committee_members_committee_id'), 'committee_members', ['committee_id'], unique=False)
    op.create_index(op.f('ix_committee_members_id'), 'committee_members', ['id'], unique=False)
    op.create_index(op.f('ix_committee_members_user_id'), 'committee_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_committee_members_user_id'), table_name='committee_members')
    op.drop_index(op.f('ix_committee_members_id'), table_name='committee_members')
    op.drop_index(op.f('ix_committee_members_committee_id'), table_name='committee_members')
    op.drop_table('committee_members')
    # ### end Alembic commands ###
