"""create publications table

Revision ID: 518ba4842ca3
Revises: 44e382e0d355
Create Date: 2026-06-25 00:35:06.790984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '518ba4842ca3'
down_revision: Union[str, Sequence[str], None] = '44e382e0d355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('publication_type', sa.String(length=100), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('journal_name', sa.String(length=255), nullable=True),
    sa.Column('conference_name', sa.String(length=255), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('openalex_id', sa.String(length=255), nullable=True),
    sa.Column('orcid_work_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['academic_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_id'), 'publications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publications_id'), table_name='publications')
    op.drop_table('publications')
    # ### end Alembic commands ###
