"""add application status history

Revision ID: 76319beb60ad
Revises: 679de73a7297
Create Date: 2026-07-23 02:34:10.637379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76319beb60ad'
down_revision: Union[str, Sequence[str], None] = '679de73a7297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=False),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_status_history_application_id'), 'application_status_history', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_status_history_changed_by'), 'application_status_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_application_status_history_id'), 'application_status_history', ['id'], unique=False)
    op.drop_constraint(op.f('roles_code_key'), 'roles', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('roles_code_key'), 'roles', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_application_status_history_id'), table_name='application_status_history')
    op.drop_index(op.f('ix_application_status_history_changed_by'), table_name='application_status_history')
    op.drop_index(op.f('ix_application_status_history_application_id'), table_name='application_status_history')
    op.drop_table('application_status_history')
    # ### end Alembic commands ###
