"""create teaching experience table

Revision ID: c6b36d9a1d29
Revises: 203fad69fedd
Create Date: 2026-07-05 19:24:30.156646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b36d9a1d29'
down_revision: Union[str, Sequence[str], None] = '203fad69fedd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teaching_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('course_title', sa.String(length=255), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('department_name', sa.String(length=255), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('semester', sa.String(length=50), nullable=True),
    sa.Column('course_level', sa.String(length=100), nullable=True),
    sa.Column('teaching_role', sa.String(length=100), nullable=True),
    sa.Column('hours_per_week', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['academic_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teaching_experience_id'), 'teaching_experience', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teaching_experience_id'), table_name='teaching_experience')
    op.drop_table('teaching_experience')
    # ### end Alembic commands ###
