"""create academic profiles table

Revision ID: cfb55733e605
Revises: 6d42f6118326
Create Date: 2026-06-21 02:20:42.310137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb55733e605'
down_revision: Union[str, Sequence[str], None] = '6d42f6118326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('academic_rank', sa.String(length=100), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('research_areas', sa.Text(), nullable=True),
    sa.Column('orcid_id', sa.String(length=50), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_academic_profiles_id'), 'academic_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_academic_profiles_id'), table_name='academic_profiles')
    op.drop_table('academic_profiles')
    # ### end Alembic commands ###
