"""add dedup key to notifications

Revision ID: dea6b094f78b
Revises: 00b7fe06c1b4
Create Date: 2026-08-31 23:05:02.052024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dea6b094f78b'
down_revision: Union[str, Sequence[str], None] = '00b7fe06c1b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('dedup_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_notifications_dedup_key'), 'notifications', ['dedup_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_dedup_key'), table_name='notifications')
    op.drop_column('notifications', 'dedup_key')
    # ### end Alembic commands ###
