"""create committee applications table

Revision ID: f8c9cfc15455
Revises: 08b2dfcaf92a
Create Date: 2026-08-03 01:57:03.619458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c9cfc15455'
down_revision: Union[str, Sequence[str], None] = '08b2dfcaf92a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committee_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('ASSIGNED', 'IN_EVALUATION', 'COMPLETED', 'CANCELLED')", name='ck_committee_application_status'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['committee_id'], ['evaluation_committees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', name='uq_committee_application_application'),
    sa.UniqueConstraint('committee_id', 'application_id', name='uq_committee_application')
    )
    op.create_index(op.f('ix_committee_applications_application_id'), 'committee_applications', ['application_id'], unique=False)
    op.create_index(op.f('ix_committee_applications_assigned_by'), 'committee_applications', ['assigned_by'], unique=False)
    op.create_index(op.f('ix_committee_applications_committee_id'), 'committee_applications', ['committee_id'], unique=False)
    op.create_index(op.f('ix_committee_applications_id'), 'committee_applications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_committee_applications_id'), table_name='committee_applications')
    op.drop_index(op.f('ix_committee_applications_committee_id'), table_name='committee_applications')
    op.drop_index(op.f('ix_committee_applications_assigned_by'), table_name='committee_applications')
    op.drop_index(op.f('ix_committee_applications_application_id'), table_name='committee_applications')
    op.drop_table('committee_applications')
    # ### end Alembic commands ###
